/*
 * JS for Introducao generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'baf83c6a-cd4a-4553-b0c3-7b3218d1e349';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "IntroducaoPros",
    "location": "#IntroducaoPros"
}, {
    "name": "PaginaInicial",
    "location": "#PaginaInicial"
}, {
    "name": "BaixarOrdemInternet_TV",
    "location": "#BaixarOrdemInternet_TV"
}, {
    "name": "ConfirmacaoCliente",
    "location": "#ConfirmacaoCliente"
}, {
    "name": "BaixarOrdemTV",
    "location": "#BaixarOrdemTV"
}, {
    "name": "BaixarOrdemTelefone",
    "location": "#BaixarOrdemTelefone"
}, {
    "name": "BaixarOrdemInternet",
    "location": "#BaixarOrdemInternet"
}, {
    "name": "Introducao",
    "location": "#Introducao"
}, {
    "name": "TipoServico",
    "location": "#TipoServico"
}, {
    "name": "IntroducaoContra",
    "location": "#IntroducaoContra"
}];

function Introducao_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_3': 'Introducao_mobilelabel_3',
        'mobilelabel_4': 'Introducao_mobilelabel_4',
        'mobilelabel_6': 'Introducao_mobilelabel_6',
        'mobilelabel_10': 'Introducao_mobilelabel_10',
        'mobilebutton_9': 'Introducao_mobilebutton_9'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'Introducao';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Introducao_onLoad = function() {
            Introducao_elementsExtraJS();

            Introducao_deviceEvents();
            Introducao_windowEvents();
            Introducao_elementsEvents();
        };

    // screen window events


    function Introducao_windowEvents() {

        $('#Introducao').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Introducao_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Introducao_elementsExtraJS() {
        // screen (Introducao) extra code

    };

    // screen elements handler


    function Introducao_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#Introducao_mobilefooter [name="mobilebutton_9"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('IntroducaoContra', {
                        reverse: false
                    });

                }
            },
        }, '#Introducao_mobilefooter [name="mobilebutton_9"]');

    };

    $(document).off("pagebeforeshow", "#Introducao").on("pagebeforeshow", "#Introducao", function(event, ui) {
        Apperyio.CurrentScreen = "Introducao";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Introducao_onLoad();
};

$(document).off("pagecreate", "#Introducao").on("pagecreate", "#Introducao", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Introducao_js();
});

function IntroducaoPros_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_7': 'IntroducaoPros_mobilelabel_7',
        'mobilelabel_2': 'IntroducaoPros_mobilelabel_2',
        'mobilelabel_3': 'IntroducaoPros_mobilelabel_3',
        'mobilelabel_5': 'IntroducaoPros_mobilelabel_5',
        'mobilelabel_8': 'IntroducaoPros_mobilelabel_8',
        'mobilelabel_9': 'IntroducaoPros_mobilelabel_9',
        'mobilelabel_10': 'IntroducaoPros_mobilelabel_10',
        'mobilelabel_11': 'IntroducaoPros_mobilelabel_11',
        'mobilebutton_6': 'IntroducaoPros_mobilebutton_6'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'IntroducaoPros';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var IntroducaoPros_onLoad = function() {
            IntroducaoPros_elementsExtraJS();

            IntroducaoPros_deviceEvents();
            IntroducaoPros_windowEvents();
            IntroducaoPros_elementsEvents();
        };

    // screen window events


    function IntroducaoPros_windowEvents() {

        $('#IntroducaoPros').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function IntroducaoPros_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function IntroducaoPros_elementsExtraJS() {
        // screen (IntroducaoPros) extra code

    };

    // screen elements handler


    function IntroducaoPros_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#IntroducaoPros_mobilefooter [name="mobilebutton_6"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('PaginaInicial', {
                        reverse: false
                    });

                }
            },
        }, '#IntroducaoPros_mobilefooter [name="mobilebutton_6"]');

    };

    $(document).off("pagebeforeshow", "#IntroducaoPros").on("pagebeforeshow", "#IntroducaoPros", function(event, ui) {
        Apperyio.CurrentScreen = "IntroducaoPros";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    IntroducaoPros_onLoad();
};

$(document).off("pagecreate", "#IntroducaoPros").on("pagecreate", "#IntroducaoPros", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    IntroducaoPros_js();
});

function PaginaInicial_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobileimage_2': 'PaginaInicial_mobileimage_2',
        'mobilelabel_4': 'PaginaInicial_mobilelabel_4',
        'mobiletextinput_7': 'PaginaInicial_mobiletextinput_7',
        'mobiletextinput_8': 'PaginaInicial_mobiletextinput_8',
        'mobilebutton_5': 'PaginaInicial_mobilebutton_5'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'PaginaInicial';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var PaginaInicial_onLoad = function() {
            PaginaInicial_elementsExtraJS();

            PaginaInicial_deviceEvents();
            PaginaInicial_windowEvents();
            PaginaInicial_elementsEvents();
        };

    // screen window events


    function PaginaInicial_windowEvents() {

        $('#PaginaInicial').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function PaginaInicial_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function PaginaInicial_elementsExtraJS() {
        // screen (PaginaInicial) extra code

    };

    // screen elements handler


    function PaginaInicial_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#PaginaInicial_mobilecontainer [name="mobilebutton_5"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('TipoServico', {
                        reverse: false
                    });

                }
            },
        }, '#PaginaInicial_mobilecontainer [name="mobilebutton_5"]');

    };

    $(document).off("pagebeforeshow", "#PaginaInicial").on("pagebeforeshow", "#PaginaInicial", function(event, ui) {
        Apperyio.CurrentScreen = "PaginaInicial";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    PaginaInicial_onLoad();
};

$(document).off("pagecreate", "#PaginaInicial").on("pagecreate", "#PaginaInicial", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    PaginaInicial_js();
});

function ConfirmacaoCliente_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_2': 'ConfirmacaoCliente_mobilelabel_2',
        'mobiletextinput_3': 'ConfirmacaoCliente_mobiletextinput_3',
        'mobiletextarea_4': 'ConfirmacaoCliente_mobiletextarea_4',
        'mobilebutton_5': 'ConfirmacaoCliente_mobilebutton_5'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'ConfirmacaoCliente';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var ConfirmacaoCliente_onLoad = function() {
            ConfirmacaoCliente_elementsExtraJS();

            ConfirmacaoCliente_deviceEvents();
            ConfirmacaoCliente_windowEvents();
            ConfirmacaoCliente_elementsEvents();
        };

    // screen window events


    function ConfirmacaoCliente_windowEvents() {

        $('#ConfirmacaoCliente').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function ConfirmacaoCliente_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function ConfirmacaoCliente_elementsExtraJS() {
        // screen (ConfirmacaoCliente) extra code

    };

    // screen elements handler


    function ConfirmacaoCliente_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#ConfirmacaoCliente_mobilecontainer [name="mobilebutton_5"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    alert("Parabéns! Obrigado por escolher a Vivo.");
                    Apperyio.navigateTo('TipoServico', {
                        reverse: false
                    });

                }
            },
        }, '#ConfirmacaoCliente_mobilecontainer [name="mobilebutton_5"]');

    };

    $(document).off("pagebeforeshow", "#ConfirmacaoCliente").on("pagebeforeshow", "#ConfirmacaoCliente", function(event, ui) {
        Apperyio.CurrentScreen = "ConfirmacaoCliente";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    ConfirmacaoCliente_onLoad();
};

$(document).off("pagecreate", "#ConfirmacaoCliente").on("pagecreate", "#ConfirmacaoCliente", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    ConfirmacaoCliente_js();
});

function BaixarOrdemInternet_TV_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_2': 'BaixarOrdemInternet_TV_mobilelabel_2',
        'mobiletextinput_3': 'BaixarOrdemInternet_TV_mobiletextinput_3',
        'mobilelabel_10': 'BaixarOrdemInternet_TV_mobilelabel_10',
        'mobiletextinput_11': 'BaixarOrdemInternet_TV_mobiletextinput_11',
        'mobilelabel_12': 'BaixarOrdemInternet_TV_mobilelabel_12',
        'mobiletextinput_13': 'BaixarOrdemInternet_TV_mobiletextinput_13',
        'mobiletextarea_6': 'BaixarOrdemInternet_TV_mobiletextarea_6',
        'mobilebutton_27': 'BaixarOrdemInternet_TV_mobilebutton_27'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'BaixarOrdemInternet_TV';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var BaixarOrdemInternet_TV_onLoad = function() {
            BaixarOrdemInternet_TV_elementsExtraJS();

            BaixarOrdemInternet_TV_deviceEvents();
            BaixarOrdemInternet_TV_windowEvents();
            BaixarOrdemInternet_TV_elementsEvents();
        };

    // screen window events


    function BaixarOrdemInternet_TV_windowEvents() {

        $('#BaixarOrdemInternet_TV').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function BaixarOrdemInternet_TV_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function BaixarOrdemInternet_TV_elementsExtraJS() {
        // screen (BaixarOrdemInternet_TV) extra code

    };

    // screen elements handler


    function BaixarOrdemInternet_TV_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#BaixarOrdemInternet_TV_mobilecontainer [name="mobilebutton_27"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('ConfirmacaoCliente', {
                        reverse: false
                    });

                }
            },
        }, '#BaixarOrdemInternet_TV_mobilecontainer [name="mobilebutton_27"]');

    };

    $(document).off("pagebeforeshow", "#BaixarOrdemInternet_TV").on("pagebeforeshow", "#BaixarOrdemInternet_TV", function(event, ui) {
        Apperyio.CurrentScreen = "BaixarOrdemInternet_TV";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    BaixarOrdemInternet_TV_onLoad();
};

$(document).off("pagecreate", "#BaixarOrdemInternet_TV").on("pagecreate", "#BaixarOrdemInternet_TV", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    BaixarOrdemInternet_TV_js();
});

function BaixarOrdemTV_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_2': 'BaixarOrdemTV_mobilelabel_2',
        'mobiletextinput_3': 'BaixarOrdemTV_mobiletextinput_3',
        'mobilelabel_12': 'BaixarOrdemTV_mobilelabel_12',
        'mobiletextinput_13': 'BaixarOrdemTV_mobiletextinput_13',
        'mobiletextarea_6': 'BaixarOrdemTV_mobiletextarea_6',
        'mobilebutton_27': 'BaixarOrdemTV_mobilebutton_27'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'BaixarOrdemTV';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var BaixarOrdemTV_onLoad = function() {
            BaixarOrdemTV_elementsExtraJS();

            BaixarOrdemTV_deviceEvents();
            BaixarOrdemTV_windowEvents();
            BaixarOrdemTV_elementsEvents();
        };

    // screen window events


    function BaixarOrdemTV_windowEvents() {

        $('#BaixarOrdemTV').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function BaixarOrdemTV_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function BaixarOrdemTV_elementsExtraJS() {
        // screen (BaixarOrdemTV) extra code

    };

    // screen elements handler


    function BaixarOrdemTV_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#BaixarOrdemTV_mobilecontainer [name="mobilebutton_27"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('ConfirmacaoCliente', {
                        reverse: false
                    });

                }
            },
        }, '#BaixarOrdemTV_mobilecontainer [name="mobilebutton_27"]');

    };

    $(document).off("pagebeforeshow", "#BaixarOrdemTV").on("pagebeforeshow", "#BaixarOrdemTV", function(event, ui) {
        Apperyio.CurrentScreen = "BaixarOrdemTV";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    BaixarOrdemTV_onLoad();
};

$(document).off("pagecreate", "#BaixarOrdemTV").on("pagecreate", "#BaixarOrdemTV", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    BaixarOrdemTV_js();
});

function BaixarOrdemTelefone_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_2': 'BaixarOrdemTelefone_mobilelabel_2',
        'mobiletextinput_3': 'BaixarOrdemTelefone_mobiletextinput_3',
        'mobilelabel_12': 'BaixarOrdemTelefone_mobilelabel_12',
        'mobiletextinput_13': 'BaixarOrdemTelefone_mobiletextinput_13',
        'mobilelabel_28': 'BaixarOrdemTelefone_mobilelabel_28',
        'mobiletextinput_29': 'BaixarOrdemTelefone_mobiletextinput_29',
        'mobiletextarea_6': 'BaixarOrdemTelefone_mobiletextarea_6',
        'mobilebutton_27': 'BaixarOrdemTelefone_mobilebutton_27'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'BaixarOrdemTelefone';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var BaixarOrdemTelefone_onLoad = function() {
            BaixarOrdemTelefone_elementsExtraJS();

            BaixarOrdemTelefone_deviceEvents();
            BaixarOrdemTelefone_windowEvents();
            BaixarOrdemTelefone_elementsEvents();
        };

    // screen window events


    function BaixarOrdemTelefone_windowEvents() {

        $('#BaixarOrdemTelefone').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function BaixarOrdemTelefone_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function BaixarOrdemTelefone_elementsExtraJS() {
        // screen (BaixarOrdemTelefone) extra code

    };

    // screen elements handler


    function BaixarOrdemTelefone_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#BaixarOrdemTelefone_mobilecontainer [name="mobilebutton_27"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('ConfirmacaoCliente', {
                        reverse: false
                    });

                }
            },
        }, '#BaixarOrdemTelefone_mobilecontainer [name="mobilebutton_27"]');

    };

    $(document).off("pagebeforeshow", "#BaixarOrdemTelefone").on("pagebeforeshow", "#BaixarOrdemTelefone", function(event, ui) {
        Apperyio.CurrentScreen = "BaixarOrdemTelefone";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    BaixarOrdemTelefone_onLoad();
};

$(document).off("pagecreate", "#BaixarOrdemTelefone").on("pagecreate", "#BaixarOrdemTelefone", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    BaixarOrdemTelefone_js();
});

function BaixarOrdemInternet_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_2': 'BaixarOrdemInternet_mobilelabel_2',
        'mobiletextinput_3': 'BaixarOrdemInternet_mobiletextinput_3',
        'mobilelabel_10': 'BaixarOrdemInternet_mobilelabel_10',
        'mobiletextinput_11': 'BaixarOrdemInternet_mobiletextinput_11',
        'mobiletextarea_6': 'BaixarOrdemInternet_mobiletextarea_6',
        'mobilebutton_27': 'BaixarOrdemInternet_mobilebutton_27'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'BaixarOrdemInternet';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var BaixarOrdemInternet_onLoad = function() {
            BaixarOrdemInternet_elementsExtraJS();

            BaixarOrdemInternet_deviceEvents();
            BaixarOrdemInternet_windowEvents();
            BaixarOrdemInternet_elementsEvents();
        };

    // screen window events


    function BaixarOrdemInternet_windowEvents() {

        $('#BaixarOrdemInternet').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function BaixarOrdemInternet_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function BaixarOrdemInternet_elementsExtraJS() {
        // screen (BaixarOrdemInternet) extra code

    };

    // screen elements handler


    function BaixarOrdemInternet_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#BaixarOrdemInternet_mobilecontainer [name="mobilebutton_27"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('ConfirmacaoCliente', {
                        reverse: false
                    });

                }
            },
        }, '#BaixarOrdemInternet_mobilecontainer [name="mobilebutton_27"]');

    };

    $(document).off("pagebeforeshow", "#BaixarOrdemInternet").on("pagebeforeshow", "#BaixarOrdemInternet", function(event, ui) {
        Apperyio.CurrentScreen = "BaixarOrdemInternet";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    BaixarOrdemInternet_onLoad();
};

$(document).off("pagecreate", "#BaixarOrdemInternet").on("pagecreate", "#BaixarOrdemInternet", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    BaixarOrdemInternet_js();
});

function TipoServico_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobileimage_7': 'TipoServico_mobileimage_7',
        'mobilegroupedbuttons_40': 'TipoServico_mobilegroupedbuttons_40',
        'mobilebutton_41': 'TipoServico_mobilebutton_41',
        'mobilebutton_42': 'TipoServico_mobilebutton_42',
        'mobilebutton_43': 'TipoServico_mobilebutton_43',
        'mobilebutton_44': 'TipoServico_mobilebutton_44'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'TipoServico';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var TipoServico_onLoad = function() {
            TipoServico_elementsExtraJS();

            TipoServico_deviceEvents();
            TipoServico_windowEvents();
            TipoServico_elementsEvents();
        };

    // screen window events


    function TipoServico_windowEvents() {

        $('#TipoServico').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function TipoServico_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function TipoServico_elementsExtraJS() {
        // screen (TipoServico) extra code

    };

    // screen elements handler


    function TipoServico_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#TipoServico_mobilecontainer [name="mobilebutton_41"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('BaixarOrdemTV', {
                        reverse: false
                    });

                }
            },
        }, '#TipoServico_mobilecontainer [name="mobilebutton_41"]');
        $(document).off("click", '#TipoServico_mobilecontainer [name="mobilebutton_42"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('BaixarOrdemInternet', {
                        reverse: false
                    });

                }
            },
        }, '#TipoServico_mobilecontainer [name="mobilebutton_42"]');
        $(document).off("click", '#TipoServico_mobilecontainer [name="mobilebutton_43"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('BaixarOrdemTelefone', {
                        reverse: false
                    });

                }
            },
        }, '#TipoServico_mobilecontainer [name="mobilebutton_43"]');
        $(document).off("click", '#TipoServico_mobilecontainer [name="mobilebutton_44"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('BaixarOrdemInternet_TV', {
                        reverse: false
                    });

                }
            },
        }, '#TipoServico_mobilecontainer [name="mobilebutton_44"]');

    };

    $(document).off("pagebeforeshow", "#TipoServico").on("pagebeforeshow", "#TipoServico", function(event, ui) {
        Apperyio.CurrentScreen = "TipoServico";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    TipoServico_onLoad();
};

$(document).off("pagecreate", "#TipoServico").on("pagecreate", "#TipoServico", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    TipoServico_js();
});

function IntroducaoContra_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_2': 'IntroducaoContra_mobilelabel_2',
        'mobilelabel_3': 'IntroducaoContra_mobilelabel_3',
        'mobilelabel_6': 'IntroducaoContra_mobilelabel_6',
        'mobilelabel_10': 'IntroducaoContra_mobilelabel_10',
        'mobilelabel_11': 'IntroducaoContra_mobilelabel_11',
        'mobilelabel_8': 'IntroducaoContra_mobilelabel_8',
        'mobilebutton_12': 'IntroducaoContra_mobilebutton_12'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'IntroducaoContra';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var IntroducaoContra_onLoad = function() {
            IntroducaoContra_elementsExtraJS();

            IntroducaoContra_deviceEvents();
            IntroducaoContra_windowEvents();
            IntroducaoContra_elementsEvents();
        };

    // screen window events


    function IntroducaoContra_windowEvents() {

        $('#IntroducaoContra').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function IntroducaoContra_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function IntroducaoContra_elementsExtraJS() {
        // screen (IntroducaoContra) extra code

    };

    // screen elements handler


    function IntroducaoContra_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#IntroducaoContra_mobilefooter [name="mobilebutton_12"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('IntroducaoPros', {
                        reverse: false
                    });

                }
            },
        }, '#IntroducaoContra_mobilefooter [name="mobilebutton_12"]');

    };

    $(document).off("pagebeforeshow", "#IntroducaoContra").on("pagebeforeshow", "#IntroducaoContra", function(event, ui) {
        Apperyio.CurrentScreen = "IntroducaoContra";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    IntroducaoContra_onLoad();
};

$(document).off("pagecreate", "#IntroducaoContra").on("pagecreate", "#IntroducaoContra", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    IntroducaoContra_js();
});